### ISSUE TITLE
Not working widget

### ISSUE THREAD

**Issue by pavkamlc** [tetsuo-repo/oh3-widgets#3]
I tried this widget on my OH3.4 and it seem like here:

![image](https://user-images.githubusercontent.com/1273709/187706433-f84fedfc-087c-4705-967b-60138ff165f1.png)

My settings:

```
component: widget:tetsuo-repo-oh3-widget-vacuum
config:
  chunkSize: "2"
  rooms: '[ 	{"icon": "table","roomId": 23,"label": "Abstellkammer"}, 	{"icon": "device_laptop","roomId": 24,"label": "Arbeitszimmer"}, 	{"icon": "drop","roomId": 20,"label": "Badezimmer"}, 	{"icon": "moon_zzz","roomId": 19,"label": "Gästezimmer"}, 	{"icon": "person","roomId": 22,"label": "Gäste-WC"}, 	{"icon": "dial","roomId": 18,"label": "Küche"}, 	{"icon": "bed_double","roomId": 16,"label": "Schlafzimmer"}, 	{"icon": "chat_bubble_2","roomId": 17,"label": "Wohnzimmer"} ]'
  itemPrefix: RoborockS6Pure
```
Can You help?
